### ISSUE TITLE
Can the main menu items be added to the right-click menu, when the main menu is hidden?

### ISSUE THREAD

**Issue by MogeiWang** [lxde/lxterminal#11]
as the title.
It would be useful if the main menu items are added to the right-click menu, or just replace the original right-click menu with the main menu items, when the main menu is hidden.
Just like [roxterm](http://roxterm.sourceforge.net/) do.

**Comment by medicalwei** [comment]
If there's no feature missing in the right-click menu (other than About) I tend not to change this.
