### ISSUE TITLE
Displaying cursive (italic) text does not work

### ISSUE THREAD

**Issue by mutluit** [lxde/lxterminal#116]
Displaying cursive text in lxterminal by using _italic escape sequence_ unfortunately does not work.

OS is Debian 11 (bullseye).
$ dpkg -l | grep -i lxterminal
ii  lxterminal                                 0.4.0-1                                   amd64        LXDE terminal emulator

See also list of terminals that support the _italic escape code_:
https://code911.top/howto/terminal-that-supports-the-ansi-italic-escape-code

**Comment by mutluit** [comment]
#From: <me>
#To: ...
#Cc: lxde-list@lists.sourceforge.net
#Date: Tue, 8 Aug 2023 12:38:16 +0200
#Subject: Re: [Lxde-list] Cursive (ie. italic) text in lxterminal

**New insights / FIX:**
-------------------

It seems to be a bug related to the "screen" program (running in lxterminal).

When printing the following in a non-"screen" terminal window then it works :
   $ printf "\e[3mitalic\e[0m\n"


Not sure whether the following TERM setting is correct as I once had xterm
installed too, but xterm is not installed anymore:

$ echo $TERM
xterm-256color

In screen this becomes:
$ echo $TERM
screen.xterm-256color

**Comment by ib** [comment]
xterm-256color is okay, that's the usual value. It expresses that lxterminal has the capabilities of an xterm with 256 colors.

These capabilities are defined (compiled) in /lib/terminfo/x/xterm-256color. screen.xterm-256color is defined in /lib/terminfo/s/screen.xterm-256color.

It seems that screen.xterm-256color can't display italic text. It displays reverse text instead.

**Comment by mutluit** [comment]
Closing issue as it works in native lxterminal. The issue is then with the "screen" program, not lxterminal.
