### ISSUE TITLE
Alt+# sent to vte after tab switch in 0.1.11

### ISSUE THREAD

**Issue by mleise** [lxde/lxterminal#12]
I'm using lxterminal 0.1.11 on Gentoo and noticed that when I switch tabs with Alt+<number>, this key combination is sent to the terminal after the switch, resulting in `(arg: <number>)` being printed in bash. Sorry for the noise if this has been fixed in more recent versions.
My vte version is 0.28.2 and my Gtk version is 2.24.28.

**Comment by medicalwei** [comment]
I found it doesn't happen in my build. If that still happens, please reopen this issue.
