### ISSUE TITLE
vim produces garbled character output on launch within lxterminal

### ISSUE THREAD

**Issue by bsdforge** [lxde/lxterminal#126]
I maintain the lxterminal port on FreeBSD. I've been informed that there is garbled
output when initiating vim within lxterminal. My investigations have determined
it's true. Further details and dialog on the matter can be reviewed at:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269188

Thanks.

**Comment by ib** [comment]
I cannot reproduce it with Devuan (lxterminal 0.4.0-2, vim 2:9.0.1378-2).

What are the dependencies (GTK, VTE) of lxterminal in FreeBSD? Do xfce4-terminal and sakura, which have been reported to be okay, have the same VTE dependencies?

**Comment by ib** [comment]
Does [this](https://github.com/vim/vim/issues/11728) perhaps help?

**Comment by bsdforge** [comment]
> Does [this](https://github.com/vim/vim/issues/11728) perhaps help?

Yes. I'm all but positive this answers the apparent anomaly. Thanks!

**Comment by ib** [comment]
It seems that setting `TERM=xterm-256color` fixes the problem with old versions of VTE. At least it did so with the vi clone I'm using.
