### ISSUE TITLE
Keybinding UI: Prompt user to hit key combinations, rather than typing the key names

### ISSUE THREAD

**Issue by mandeeps708** [lxde/lxterminal#13]
I tried to find some config. or preferences regarding setting zoom in/out keybindings (keyboard shortcuts) in lxterminal, but couldn't find it. I am talking about like I used gnome-terminal in which we can do `Ctrl Shift +` to zoom in. Now I have to go to `Preferences` to set the font size manually.

If there is any workaround then please help. Thank you.

Using lxterminal on ArchBang.

**Comment by medicalwei** [comment]
Sorry for late reply.
The default key bindings are:

Zoom in: <CTRL>plus
Zoom out: <CTRL>underscore
Zoom reset: <CTRL>parenright

**Comment by mandeeps708** [comment]
Not working on mine side.

**Comment by hurzl** [comment]
I cannot change these shortcuts. Why?

**Comment by mandeeps708** [comment]
@hurzl you mean these above shortcuts works for you but you want to change them. Right?

**Comment by hurzl** [comment]
Yes, but the default value is always filled in automatically

**Comment by medicalwei** [comment]
What key combination do you want to use?

In our current implementation it will use `gtk_accelerator_parse` to parse key combinations, which key names are listed here:
https://github.com/GNOME/gtk/blob/master/gdk/keyname-table.h

**Comment by hurzl** [comment]
Ok, I have to type "minus" instead of "-"! :-1:

**Comment by medicalwei** [comment]
Theoretically it is far better to prompt user to press keys for setting it up though.

*putting this into To-do*
