### ISSUE TITLE
Critical message when open lxterminal window or tab

### ISSUE THREAD

**Issue by jeffreyhc** [lxde/lxterminal#20]
When I open lxterminal in Ubuntu default terminal, I found there are some critical message showed on the default terminal.
![critical1](https://cloud.githubusercontent.com/assets/17449636/15885638/fe92c3ec-2d8a-11e6-9d7d-df6998a31402.PNG)
The message "GLib-CRITICAL **: g_key_file_set_string: assertion 'key_file != NULL' failed" shows when the lxterminal just opened.
![critical2](https://cloud.githubusercontent.com/assets/17449636/15885662/349c1470-2d8b-11e6-9ae2-8184092534c9.PNG)
And the message "GLib-CRITICAL **: g_str_has_prefix: assertion 'str != NULL' failed" shows when opening a new tab in lxterminal.

**Comment by mtasaka** [comment]
My patch should fix this issue.
