### ISSUE TITLE
Unable to renaming "tabs" titles

### ISSUE THREAD

**Issue by lucaconte** [lxde/lxterminal#31]
Distro: Debian Testing (LXDE)
Shipped version: 0.3.0

I'm unable to change the window/tab title with "CRTL-SHIT-I": A pop-up appears but the "ok" button is missing and pressing ENTER nothing happens

**Comment by medicalwei** [comment]
Duplicate with #30, and has been fixed.

**Comment by lucaconte** [comment]
close #31
