### ISSUE TITLE
Allow temporarily disabling ESC character sequences

### ISSUE THREAD

**Issue by HybridDog** [lxde/lxterminal#34]
I'd like to have a setting to disallow ESC character usage temporary. When I'm on a server with multiple users via ssh, someone could write "\033P" (where \033 is the ESC character) to me and then my terminal is broken. (Test it with $ echo -e "\033P")

**Comment by medicalwei** [comment]
Would be good if migrating to GTK+3.
https://bugzilla.gnome.org/show_bug.cgi?id=676090

"\033P" does not hang in LXTerminal with GTK+3 and libvte 2.91 in my environment.

**Comment by medicalwei** [comment]
Also I am afraid that libvte doesn't have a switch to omit control sequence.
[libvte3 seems removed ISO2022 support](https://bugzilla.gnome.org/show_bug.cgi?id=732586), and \033P does nothing in the libvte3 implementation now.
