### ISSUE TITLE
Uyyuu

### ISSUE THREAD

**Issue by kanang** [lxde/lxterminal#37]
12 lines (10 sloc)  349 Bytes
Developer:
Fred Chien <cfsghost@gmail.com>
Alessandro Pellizzari <alex_shu@users.sourceforge.net>
Micahel <metsger@users.sourceforge.net>
Yotam Medini <yotam.medini@gmail.com>
Liu Yubao <yubao.liu@gmail.com>
Marty Jack <martyj19@comcast.net>
Martin Bagge <brother@bsnet.se>

Icon:
Taken from "nuoveXT 2" icon theme created by Alexandre Moore (saki)
© 2017 GitHub, Inc.

**Comment by medicalwei** [comment]
??? ???

**Comment by medicalwei** [comment]
What's this?
