### ISSUE TITLE
Can't compile: several files missing

### ISSUE THREAD

**Issue by sovietspaceship** [lxde/lxterminal#4]
$ autoconf
$ ./configure
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
[...]
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating data/Makefile
config.status: creating data/lxterminal.conf
config.status: error: cannot find input file: `po/Makefile.in.in'
$ make
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '*/lxterminal'
Making all in src
make[2]: Entering directory '*/lxterminal/src'
Makefile:391: .deps/lxterminal-lxterminal.Po: No such file or directory
Makefile:392: .deps/lxterminal-preferences.Po: No such file or directory
Makefile:393: .deps/lxterminal-setting.Po: No such file or directory
Makefile:394: .deps/lxterminal-unixsocket.Po: No such file or directory
make[2]: *** No rule to make target '.deps/lxterminal-unixsocket.Po'.  Stop.
make[2]: Leaving directory '*/lxterminal/src'
Makefile:377: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '*/lxterminal'
Makefile:317: recipe for target 'all' failed
make: *** [all] Error 2

0.1.11 compiles just fine. If you made any changes to the build process, please, update the README. In any case, it is clear that something is broken.

**Comment by medicalwei** [comment]
Try these below as I can build the code without problem:
``` bash
git clean -f -d -x
./autogen.sh
./configure
make
```

**Comment by sovietspaceship** [comment]
Thanks. It works. For some reason, when pulling from git it does not compile for me, I have to do git clean first

**Comment by sovietspaceship** [comment]
Nice. Now make complains again
    Error: you need to run configure with '--enable-man'
           in order to regenerate man pages.

After git clean, ./autogen.sh and ./configure --enable-man.

**Comment by medicalwei** [comment]
I think we just made it as an "error" for manpage generation. It just complains but the binary is generated so you can install it.

**Comment by medicalwei** [comment]
I am going to close it as... it is our convention to spit out error when not generating manpage.
