### ISSUE TITLE
Is it possible set window size?

### ISSUE THREAD

**Issue by netroby** [lxde/lxterminal#6]
Is it possible set window size?

Once we open new terminal window, the size too small, may we custom set the default windows size ? 

such as 800x600 px or what ever.

**Comment by medicalwei** [comment]
The default window (geometry) size is not included as an option but is implemented in command line.
(You can set the size in the shell script or `.desktop` file)

If you still need it in the settings window, please reply.

**Comment by netroby** [comment]
If you could provided setting options , it will be very nice, and friendly for us.
Konsole had good setting options.

**Comment by netroby** [comment]
Thanks. I would like to compile a lxterminal for test.
