### ISSUE TITLE
Install document need improve

### ISSUE THREAD

**Issue by netroby** [lxde/lxterminal#7]
I wan to contribe the lxterminal install document

if we want to compile from sources, we need to prepare some dependency libarary

I am testing under Ubuntu

```
apt-get install autoconf xsltproc docbook-xml docbook-xsl
apt-get build-dep lxterminal
./autogen.sh
./configure --prefix=/usr --enable-man
make && sudo make install

```

**Comment by netroby** [comment]
The are several bugs when run ./autogen.sh


```
autoconf
configure.ac:10: error: possibly undefined macro: AC_PROG_INTLTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:87: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT

```

and configure got problem
```
./configure --prefix=/usr
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
./configure: line 2718: AC_PROG_INTLTOOL: command not found
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for library containing strerror... none required
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
./configure: line 5014: syntax error near unexpected token `gtk,'
./configure: line 5014: `PKG_CHECK_MODULES(gtk, $gtk_modules)'

```

**Comment by netroby** [comment]
@medicalwei would you please take a look?

**Comment by medicalwei** [comment]
You can actually look it up in debian/control file from the ubuntu source
(via `apt-get source` or `debcheckout`).
I looked it up in a Debian repo, and its `Build-Depends` says:
```
Build-Depends:
 debhelper (>= 9), autotools-dev, intltool, libglib2.0-dev,
 libgtk2.0-dev, libvte-dev
```


On Thu, Nov 5, 2015 at 1:35 PM, netroby <notifications@github.com> wrote:

> I wan to contribe the lxterminal install document
>
> if we want to compile from sources, we need to prepare some dependency
> libarary
>
> I am testing under Ubuntu
>
> apt-get install autoconf
> apt-get build-dep lxterminal
> ./autogen.sh
> ./configure --prefix=/usr
> make && sudo make install
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxterminal/issues/7>.
>



-- 
Yao Wei

**Comment by medicalwei** [comment]
`autotools` and `intltool` is needed if you want to build from git source. The packaged source shouldn't need `./autogen.sh`.

**Comment by medicalwei** [comment]
Could you give me what distro you are using? In that way I can try to find out what package you are missing if possible.

**Comment by netroby** [comment]
```
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal/po'
Making all in data
make[2]: Entering directory '/home/huzhifeng/workspace/netroby/lxterminal/data'
sed 's/<!--.*-->//' < lxterminal-preferences.glade | sed ':a;N;$!ba;s/ *\n *</</g' > lxterminal-preferences.ui
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal/data'
Making all in man
make[2]: Entering directory '/home/huzhifeng/workspace/netroby/lxterminal/man'

Error: you need to run configure with '--enable-man'
       in order to regenerate man pages.

Makefile:536: recipe for target 'lxterminal.1' failed
make[2]: *** [lxterminal.1] Error 1
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal/man'
Makefile:399: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal'
Makefile:340: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by netroby** [comment]
Lubuntu 15.10,

**Comment by netroby** [comment]
Yes, i am try to build from git source, i see your just patch , want to try it

**Comment by medicalwei** [comment]
That manpage error is intended (I don't know the reason why. Maybe it is our "convention"). If you need manpage, please add `--enable-man`  in `./configure` as reported.

**Comment by netroby** [comment]
Yes, i tried add --enable-man, but still report the same problem.

**Comment by medicalwei** [comment]
Then you miss some dependencies for it: xsltproc, docbook-xml, docbook-xsl

**Comment by netroby** [comment]
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal/po'
Making all in data
make[2]: Entering directory '/home/huzhifeng/workspace/netroby/lxterminal/data'
sed 's///' < lxterminal-preferences.glade | sed ':a;N;$!ba;s/ *\n *</</g' > lxterminal-preferences.ui
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal/data'
Making all in man
make[2]: Entering directory '/home/huzhifeng/workspace/netroby/lxterminal/man'
nonet http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl lxterminal.xml        
/bin/bash: nonet: command not found
Makefile:533: recipe for target 'lxterminal.1' failed
make[2]: [lxterminal.1] Error 127 (ignored)
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal/man'
make[2]: Entering directory '/home/huzhifeng/workspace/netroby/lxterminal'
make[2]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal'
make[1]: Leaving directory '/home/huzhifeng/workspace/netroby/lxterminal'


Seems lose nonet

**Comment by medicalwei** [comment]
Maybe, if you have `devscripts` installed, you can generate build dependency virtual package by using mk-build-deps on the project directory.

**Comment by netroby** [comment]
Thanks, trying to install dependencies

**Comment by netroby** [comment]
i found a bug in man/Makefile

**Comment by netroby** [comment]
Thanks. i success build the new lxterminal , works very well, and the window size configure options working well

**Comment by medicalwei** [comment]
I am going to close the issue as the pull request #8 is committed.
