### ISSUE TITLE
LXTerm 0.2.0 fails to properly display neovim

### ISSUE THREAD

**Issue by phansel** [lxde/lxterminal#72]
LXTerm shows random characters that do not go away when neovim is run. Explanation of issue is here:

https://github.com/neovim/neovim/issues/10240

**Comment by egmontkob** [comment]
LXTerminal can be compiled against GTK2 and in turn an 8 year old, no longer maintained VTE doing the terminal emulation; or GTK3 with a fresh VTE. The issue is only present with the old VTE, and won't be fixed. Use GTK3.
