### ISSUE TITLE
lxterminal crashes when closing a single tab

### ISSUE THREAD

**Issue by amboxer21** [lxde/lxterminal#75]
If I open an lxterminal instance and close out a single tab, the entire lxterminal crashes. 

I opened a bug at the Gentoo bug site as well https://bugs.gentoo.org/690958

** Logs: **
anthony@anthony ~ $ sudo egrep --color -ai 'lxterm.*(general protection|segfault)' /var/log/messages
Jun  7 20:11:51 anthony kernel: lxterminal[3074]: segfault at 559658b0ab40 ip 00007f24773ec9e0 sp 00007ffc1cc24798 error 4 in libc-2.29.so[7f24772a0000+15a000]
Jul  3 20:31:52 anthony kernel: lxterminal[3092]: segfault at 30 ip 0000560b9d2a5261 sp 00007ffd43ee6700 error 4 in lxterminal[560b9d29a000+12000]
Jul 19 21:19:28 anthony kernel: lxterminal[7676]: segfault at a0 ip 00007f32a03f0b76 sp 00007ffdbd8f4858 error 4 in libgtk-3.so.0.2404.4[7f32a02fe000+351000]
Jul 20 10:56:58 anthony kernel: lxterminal[3167]: segfault at fe2cf82 ip 00007fb4a6b943ce sp 00007fff1e433ff0 error 4 in libglib-2.0.so.0.5800.3[7fb4a6b2a000+11b000]
Jul 20 13:49:40 anthony kernel: lxterminal[4665]: segfault at 8 ip 00007fb62114d2ff sp 00007ffd551f69f0 error 6 in libglib-2.0.so.0.5800.3[7fb6210e2000+11b000]
Jul 21 13:57:00 anthony kernel: lxterminal[3134]: segfault at 9e72 ip 00007f15809b917a sp 00007ffc6175d7d0 error 4 in libglib-2.0.so.0.5800.3[7f158094e000+11b000]
Jul 21 19:15:59 anthony kernel: lxterminal[3341]: segfault at 4ec8 ip 00007fd0c3a6c17a sp 00007fffd2727f70 error 4 in libglib-2.0.so.0.5800.3[7fd0c3a01000+11b000]
Jul 27 14:56:14 anthony kernel: lxterminal[3090]: segfault at 1 ip 00007fd51f49e17a sp 00007fff8080bf20 error 4 in libglib-2.0.so.0.5800.3[7fd51f433000+11b000]
Jul 27 15:19:44 anthony kernel: lxterminal[12515]: segfault at 8 ip 00007f6668076426 sp 00007ffe4c03d460 error 6 in libglib-2.0.so.0.5800.3[7f666800c000+11b000]
Jul 27 15:38:10 anthony kernel: lxterminal[1516]: segfault at 7fcced7661f0 ip 00007fcb88f69810 sp 00007ffdd611cac8 error 4 in libc-2.29.so[7fcb88e1d000+15a000]
Jul 27 16:33:45 anthony kernel: traps: lxterminal[13545] general protection fault ip:557c3e16f436 sp:7fff5b42b940 error:0 in lxterminal[557c3e16b000+9000]
Jul 27 16:59:39 anthony kernel: traps: lxterminal[14033] general protection fault ip:7f2a95ed2c4c sp:7ffc66d28610 error:0 in libgobject-2.0.so.0.5800.3[7f2a95ea8000+32000]
Jul 27 16:59:44 anthony kernel: traps: lxterminal[13520] general protection fault ip:7f6b3c555c4c sp:7ffe3eab11d0 error:0 in libgobject-2.0.so.0.5800.3[7f6b3c52b000+32000]
Jul 27 21:03:59 anthony kernel: traps: lxterminal[3155] general protection fault ip:555ee8541436 sp:7ffc03f6fc40 error:0 in lxterminal[555ee853d000+9000]
Jul 28 21:12:05 anthony sudo[5187]:  anthony : TTY=pts/2 ; PWD=/home/anthony ; USER=root ; COMMAND=/bin/egrep --color -ai lxterm.*(general protection|segfault) /var/log/messages
anthony@anthony ~ $

anthony@anthony ~ $ eix -I sys-libs/glibc
[I] sys-libs/glibc
     Available versions:  (2.2) [M]~2.19-r2^s [M]2.23-r4^s [M]~2.24-r4^s [M]2.25-r11^s [M]2.26-r7^s [M]2.27-r6^s 2.28-r6^s 2.29-r2^s **9999^s
       {audit caps cet compile-locales custom-cflags debug doc gd hardened headers-only +multiarch multilib nscd profile +rpc selinux split-usr +ssp +static-libs suid systemtap test vanilla}
     Installed versions:  2.29-r2(2.2)^s(04:55:31 PM 07/27/2019)(multiarch multilib split-usr ssp -audit -caps -cet -compile-locales -doc -gd -headers-only -nscd -profile -selinux -suid -systemtap -test -vanilla)
     Homepage:            https://www.gnu.org/software/libc/
     Description:         GNU libc C library

anthony@anthony ~ $ eix -I lxde-base/lxterminal
[I] lxde-base/lxterminal
     Available versions:  0.3.1 ~0.3.2 {gtk3}
     Installed versions:  0.3.1(04:33:12 PM 07/27/2019)(gtk3)
     Homepage:            https://wiki.lxde.org/en/LXTerminal
     Description:         Lightweight vte-based tabbed terminal emulator for LXDE

anthony@anthony ~ $

anthony@anthony ~ $ ldd -v /usr/lib64/libglib-2.0.so.0.5800.3
	linux-vdso.so.1 (0x00007ffc076f3000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f5f848ba000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5f84897000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5f846c7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5f84a76000)

	Version information:
	/usr/lib64/libglib-2.0.so.0.5800.3:
		libpthread.so.0 (GLIBC_2.12) => /lib64/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /lib64/libpthread.so.0
		libc.so.6 (GLIBC_2.9) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.3) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.16) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.8) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.10) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.15) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
	/lib64/libpcre.so.1:
		libpthread.so.0 (GLIBC_2.2.5) => /lib64/libpthread.so.0
		libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
	/lib64/libpthread.so.0:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
	/lib64/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
anthony@anthony ~ $

**Comment by amboxer21** [comment]
Seems compiling without gtk3 fixes the issue. Though compiling with gtk2 breaks the color scheme and you must set it manually.

**Comment by medicalwei** [comment]
The color theme issue is due to color codes stored by GTK3 cannot be read
by GTK2.

**Comment by amboxer21** [comment]
Seems updating to version unstable version 0.3.2 fixes the issue.

anthony@anthony ~ $ eix lxterminal
[I] lxde-base/lxterminal
     Available versions:  0.3.1 (~)0.3.2 {gtk3}
     Installed versions:  0.3.2(11:15:24 AM 07/29/2019)(gtk3)
     Homepage:            https://wiki.lxde.org/en/LXTerminal
     Description:         Lightweight vte-based tabbed terminal emulator for LXDE

anthony@anthony ~ $
