### ISSUE TITLE
Lxterminal can't display utf8 text?

### ISSUE THREAD

**Issue by math345** [lxde/lxterminal#76]
Type ls cmd, then it can't display the utf8  names of files.

**Comment by jeffmcneill** [comment]
![Screenshot from 2020-10-28 04-41-00](https://user-images.githubusercontent.com/3119827/97365157-cfe72780-18d7-11eb-9d59-f7b13d449600.png)

works for me...

**Comment by FinboySlick** [comment]
I've seen this problem happen when VTE is an older version.  If you're still experiencing problem, could you specify the version of lxterminal, vte and your distro?

**Comment by jeffmcneill** [comment]
Probably can close this, original poster has not responded in ~6 months and the item was opened over 1.5 years ago.

**Comment by FinboySlick** [comment]
Will re-open if we hear back.  Was probably an old VTE issue.
