### ISSUE TITLE
Would you please add flags to display version of LXterminal?

### ISSUE THREAD

**Issue by netroby** [lxde/lxterminal#9]
Would you please add flags to display version of LXterminal?
For example

lxterminal -v    [ to show short version information ]

lxterminal -V   [ to show detail version information ]

**Comment by medicalwei** [comment]
That's actually a bit redundant as it can be shown from the menu. I am wondering what it is for.

**Comment by netroby** [comment]
I am talking about the version information display in terminate. (XTERM) , not the GUI

**Comment by netroby** [comment]
I want to wrote some scripts, that auto upgrade lxterminate if the version not match the specified version.

For example

```bash
if [ $VERSION -lt 2 ]; then
   // Do upgrade
fi
```

**Comment by netroby** [comment]
Amazing , thanks for your hard work!!
